package:
  name: netgen
  version: 6.1

source:
  path: ../netgen-6.1-src

build:
  detect_binary_files_with_prefix: True
  number: 1
  features:
    - vc9               [win and py27]
    - vc10              [win and py34]
    - vc14              [win and py35]

requirements:
  build:
    - patch             [win]
    - ninja
    - cmake
    - oce ==0.17.2
    - gcc-5 ==5.4.0     [linux or osx]
    - binutils ==2.26   [linux]

  run:
    - oce ==0.17.2

about:
  home: https://sourceforge.net/projects/netgen-mesher/
  license: LGPLv2
  summary: NETGEN is an automatic 3d tetrahedral mesh generator.
